#workfLow 名稱
name : CI
# 什麼情況下觸發 workflow
on:
  #對於main branch 建立Branch 與Pull Request 時觸發workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  #允許你 Action 頁簽上手動執行 workflow
  workflow_dispatch:
  
# Job 可以循序或平行執行
jobs:
  #這個 workflow 只有一個job.名稱為"build"
  build:
    runs-on: ubuntu-latest
    
    #作為Job的一部分·Steps 會循序執行一連串的動作
    steps:
    #在$GITHUB WORKSPACE 下簽出您的存儲庫,以便您的工作可以訪問它
    - uses: actions/checkout@v2
    
    #在Runner 上使用 shell 顯示出 Hello world
    - name: Run a one-line script
    run: echo Hello, world!
    
    # 執行一組的指令
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
